# Site settings
title: Entropy Day
#email: N.Lawrence@sheffield.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  A cross departmental and faculty discussion meeting on Entropy for the entire University..
baseurl: "/ed2016" # the subpath of your site, e.g. /blog/
url: "http://opendsi.cc" # the base hostname & protocol for your site
twitter_username: datascienceshef
github_username:  sods


# Build settings
future: true

permalink: "/:categories/:title.html"
banner: nice_conference_banner.jpeg

analytics:
  google:
    tracking_id: UA-62964644-1
    
youtube:
  height: 315
  width: 560

conference:
  room: G14
  venue: 9 Mappin Street
  location: Sheffield, UK
  name: Entropy Day
  year: 2016
  month: May
  dates:
  - 2016-05-23
  draft: true # set to True if the programme is draft only.
  hosts:
  organizers:
  - name: Dagmar Divjak
    url: "https://www.sheffield.ac.uk/russian/staff/profiles/divjakd"
  - name: Neil Lawrence
    url: "http://inverseprobability.com"

map:
  show: True
  mapbox:
    latitude: 53.3819 # latitude of map center
    longitude: -1.4793 # longitude of map center
    map_id: lawrennd.pnghko26 # mapbox id
    access_token: "pk.eyJ1IjoibGF3cmVubmQiLCJhIjoiY2luNmUyN2psMDB2MXdlbTJib3dmM3BsOSJ9.OpJ8Nc0xOGyNKZtAAsLECQ" # mapbox access token
    zoom_level: 17
    width: 100%
    height: 500px
